# Generated by Django 3.0.2 on 2020-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
