# Generated by Django 3.0.2 on 2020-02-04 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lessonID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Lesson'),
            preserve_default=False,
        ),
    ]
