# Generated by Django 3.0.2 on 2020-02-04 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_quiz_lessonid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='lessonID',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quizID',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.Quiz'),
            preserve_default=False,
        ),
    ]
