# Generated by Django 3.0.2 on 2020-02-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_award_award_unlocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_desc',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
