# Generated by Django 3.0.2 on 2020-02-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_award_award_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='award_url',
            field=models.CharField(default='text', max_length=255),
            preserve_default=False,
        ),
    ]
