# Generated by Django 3.0.2 on 2020-02-23 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0013_auto_20200223_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='lesson_complete',
        ),
        migrations.AddField(
            model_name='lesson',
            name='user',
            field=models.ManyToManyField(related_name='lesson', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LessonComplete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_complete', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Lesson')),
                ('user', models.ManyToManyField(related_name='lessonComplete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='lesson_complete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.LessonComplete'),
        ),
    ]
