# Generated by Django 3.0.2 on 2020-02-23 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_lessoncomplete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessoncomplete',
            options={'verbose_name_plural': 'Lesson Complete'},
        ),
    ]
