# Generated by Django 3.0.2 on 2020-02-23 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200223_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='lesson_complete',
        ),
        migrations.RemoveField(
            model_name='award',
            name='user',
        ),
    ]
