# Generated by Django 3.0.2 on 2020-02-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0024_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepicture',
            name='user',
        ),
        migrations.CreateModel(
            name='ProfilePictureChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.ProfilePicture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
