# Generated by Django 3.0.2 on 2020-02-26 17:35

from django.db import migrations, models
import django.db.models.deletion
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_auto_20200226_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilepicture',
            options={'verbose_name_plural': 'Profile Pictures'},
        ),
        migrations.AlterModelOptions(
            name='profilepicturechosen',
            options={'verbose_name_plural': 'Profile Pictures Chosen'},
        ),
        migrations.AlterField(
            model_name='profilepicturechosen',
            name='profile_picture',
            field=models.ForeignKey(default=pages.models.getDefaultProfilePic, on_delete=django.db.models.deletion.CASCADE, to='pages.ProfilePicture'),
        ),
    ]
