# Generated by Django 3.0.2 on 2020-03-01 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_auto_20200226_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAwardChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_chosen', models.BooleanField(default=False)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.AwardUnlocked')),
            ],
            options={
                'verbose_name_plural': 'Profile Awards Chosen',
            },
        ),
    ]
