# Generated by Django 3.0.2 on 2020-03-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_profileawardchosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardunlocked',
            name='award_chosen',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ProfileAwardChosen',
        ),
    ]
