# Generated by Django 3.0.2 on 2020-03-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_auto_20200301_2157'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
