# Generated by Django 3.0.2 on 2020-03-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friend_profile_picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pages.ProfilePictureChosen'),
            preserve_default=False,
        ),
    ]
