# Generated by Django 3.0.2 on 2020-03-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_friend_friend_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend_profile_picture',
        ),
    ]
